### ISSUE TITLE
Example input .csv files

### ISSUE THREAD

**Issue by smirarab** [esayyari/DiscoVista#1]
Please add examples of the clades definition and annotation files for the 1kp dataset to the repo and refer to them in the appropriate places from the README.

**Comment by Aannaw** [comment]
I can not find the _annotation-hypo.tx_t in the _paramete_r folder either till now.  Is it the same as the annotation file as _astral_. I am confused "**you need an annotation file (“-a”) where you have one line per each species which assigns each species to a major split (clade) separated by tabs**" in the _readme._
Looking forward to responses.

**Comment by Aannaw** [comment]
I can not find the _annotation-hypo.txt_  in the _parameter_ folder either till now. Is it the same as the annotation file as _astral_. I am confused "you need an annotation file (“-a”) where you have one line per each species which assigns each species to a major split (clade) separated by tabs" in the readme.
Looking forward to responses.

**Comment by smirarab** [comment]
Have you checked out the [the example folder](../tree/master/example/) and particularly [this](../tree/master/example/1KP/parameters) folder?

**Comment by Aannaw** [comment]
Thank you foe your prompt response.
I have checked the folder again, and find the annotation.txt.  Are there some parameters which can display the all three tree topologial around focna linternal branches generated by DiscoVisto?
looking forward to responses.

**Comment by Aannaw** [comment]
Thank you very much fo​r your prompt response.
I have checked the folder again, and find the annotation.txt. Are ​there some parame​ters whic​h can display t​he​ all three tre​e topologies ​ corresponding to the bar plot generated by DiscoVisto. The bar plot describes the frequency of three topologies around focal internal branches.​
looking forward to responses.

**Comment by smirarab** [comment]
Yes, following the example folder tutorial should help you reproduce those results.
