### ISSUE TITLE
No Tree Found Error

### ISSUE THREAD

**Issue by simone-says** [esayyari/DiscoVista#12]
`please check the path to data direcotry`

`No tree found! please follow the structure specified in the examples!`

For some reason it’s not recognizing my tree files. I've set up a directory and subdirectory according to the examples, but I keep getting these 2 error messages. I only have 2 tree files that I'm attempting to compare, so only 2 subdirectories. It’s finding the results directory because it starts to create output files, but they are empty. 

This is what I ran last:
`docker run  -v /Users/simonegable/Desktop/Tollis_Lab/squamate_turtle_phylogenomics/TURTLES/DiscoVista:/data esayyari/discovista discoVista.py -c parameters/turtle-clade-defs.txt -a parameters/annotation.txt -p species/ -t 95 -m 0 -o species/results`

**Comment by esayyari** [comment]
Thanks for using DiscoVista. My guess is that you have a typo in your naming convention. Can you please double check that you follow this convention: path/<MODEL_CONDITION>-<DST>/estimated_species_tree.tree. If this didn't fix your problem, can you please share your data with me. I'll take a look
