### ISSUE TITLE
Changes in supported/rejected clades across dataset comparisons

### ISSUE THREAD

**Issue by mkandziora** [esayyari/DiscoVista#13]
Dear Developers,

Thanks for developing some tools to visualize differences across phylogenomic datasets. 

I was using the gene tree discordance analysis tool (M1) to visualize differences between different filtering settings. One of the filtering settings occurs in two comparisons I did. While in one of the comparison the amount of strongly rejected gene trees is about 50% this drops down to about 25% if I compare that setting to other differently filtered datasets.

The command I am using is the following:
sudo docker run -v /PATHTO/DiscoVista:/data esayyari/discovista discoVista.py -c clade_def  -p PATH_TO_GENETREES -t 50 -k 1 -m 1 -o M1_filtering1 -g out -a annotation.txt 

I was doing some testing and it seems to be related to the different clade_def files I am using. 
In the first comparison, I compare the effect of badly sampled taxa - so the clade_def file contains more taxa as some of the datasets include more taxa. In the second comparison, I use one of the filters from the first comparison and use it to then do a different set of sample filtering (where I look for gene flow in samples). For this, the clade_def has fewer taxa, as I removed all of the ones I filtered out using my first approach. 

How does the number of taxa in the clade_def file influence the measure of discordance? According to my understanding from the publication and tutorial, this should only depend on the bootstrap threshold value (-t). Do I miss a crucial point?

Thanks for the advice,
Martha

**Comment by smirarab** [comment]
Martha, I do not think I fully understand the issue you are describing. Here are some information that you may find useful. 

The `-m 1` option tests whether a group that you define is **monophyletic** or not. A group is monophyletic if there is a clade in the tree that includes these species and no other species. So, if the tree is `(((A,B),C),D)`, then, groups `{A,B}`, `{A,B,C}` and `{A,B,C,D}` are monophyletic; however, `{A,B,D}` is NOT monophyletic. 

If you change what species are defined in a clade without also changing the gene trees, of course, the monophyly can change. 

Not sure if this answers your question but I hope it does.

**Comment by mkandziora** [comment]
Hi, Thank you for your reply. Not sure, I get it right: you mean, if from your example (((A,B),C),D), I have one gene tree showing ((A,B),D), because C was never present in that gene tree, it will be treated as not monophyletic?

Let's say I am having 10 taxa (A-J). In my first comparison, I define my clades based on all taxa (A-J) and have 5 different filtering settings - each removes let's say 2 taxa but different ones. I run the gene tree discordance method (m1) and get for treatment X 50% highly conflicting gene trees. I then use treatment X and compare it to another set of analyses, but adapted my clade definition file to exclude the 2 taxa  I removed from treatment X (A-H). In that comparison the number of highly conflicting gene trees drops to 25%.

If I get it right it means, I can only compare gene tree discordance across different analysis methods, but not across different sampling strategies (e.g. after excluding hybrids, badly sampled samples, etc.) as missing data is treated as non-monophyletic?

**Comment by smirarab** [comment]
> if from your example (((A,B),C),D), I have one gene tree showing ((A,B),D), because C was never present in that gene tree, it will be treated as not monophyletic?

No if `C` is missing from the gene tree, it's fine. It will show as monophyletic. The exception is if only one taxon is left from a clade. 

> Let's say I am having 10 taxa (A-J). In my first comparison, I define my clades based on all taxa (A-J) and have 5 different filtering settings - each removes let's say 2 taxa but different ones. I run the gene tree discordance method (m1) and get for treatment X 50% highly conflicting gene trees. I then use treatment X and compare it to another set of analyses, but adapted my clade definition file to exclude the 2 taxa I removed from treatment X (A-H). In that comparison the number of highly conflicting gene trees drops to 25%.

Again, I am not sure if I understand this. Are you saying:

- Analysis 1: gene trees include A-H, clade definitions include A-J, you get 50% conflicting with the clade
- Analysis 2: gene trees include A-H, clade definitions include A-H, you get 25% conflicting with the clade?

> If I get it right it means, I can only compare gene tree discordance across different analysis methods, but not across different sampling strategies (e.g. after excluding hybrids, badly sampled samples, etc.) as missing data is treated as non-monophyletic?

Missing data is handled fine. 

Sending me some examples will help me understand what you are asking. I am not quite sure right now.

**Comment by mkandziora** [comment]
Ok, I found my issue when I was preparing a small example. I overlooked one taxon that was missing in one of the clade definitions, which lead to the differences in conflicting trees across my two comparisons. Thanks a lot for the responses and explanation on missing data.
